services:
  iris:
    build: .
    container_name: miles-iris
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
      - API_URL=http://localhost:3002
      - MCP_API_URL=${MCP_API_URL:-http://host.docker.internal:3000/api/mcp}
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5:7b}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-5-sonnet-20241022}
    volumes:
      # Persist SQLite database
      - iris-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - miles-network

volumes:
  iris-data:
    driver: local

networks:
  miles-network:
    driver: bridge
